version: '3.9'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - gerenciamento
    networks:
      - EmailNetwork

  db_gerenciamento:
    image: postgres:16
    container_name: db_gerenciamento
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./gerenciamento/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d agendamento"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - EmailNetwork

  gerenciamento:
    build: ./gerenciamento/src
    container_name: gerenciamento
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=db_gerenciamento
      - DATABASE_PORT=5432
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      db_gerenciamento:
        condition: service_healthy
      networks:
      - EmailNetwork

  envio:
    build: ./envio
    container_name: envio
    ports:
      - "5001:3000"
    environment:
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
    networks:
      - EmailNetwork

volumes:
  pgdata:

networks:
  EmailNetwork:
    driver: bridge 