version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      args:
        BACKEND_URL: ${FRONTEND_BACKEND_URL}
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      - BACKEND_URL=${FRONTEND_BACKEND_URL}
    depends_on:
      - gerenciamento
    networks:
      - EmailNetwork

  db_gerenciamento:
    image: postgres:16
    container_name: db_gerenciamento
    environment:
      - POSTGRES_DB=${DATABASE_NAME} 
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./gerenciamento/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - EmailNetwork

  gerenciamento:
    build:
      context: ./gerenciamento
      dockerfile: src/Dockerfile
    container_name: gerenciamento
    ports:
      - "5000:8080"
    environment:
      - DATABASE_CONNECTION=Host=${DATABASE_HOST};Port=${DATABASE_PORT};Database=${DATABASE_NAME};Username=${DATABASE_USER};Password=${DATABASE_PASSWORD}
      - EMAIL_ENVIO_URL=${EMAIL_ENVIO_URL}
    depends_on:
      - db_gerenciamento
    networks:
      - EmailNetwork

  envio:
    build: ./envio
    container_name: envio
    ports:
      - "5001:3000"
    environment:
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
    networks:
      - EmailNetwork

volumes:
  pgdata:

networks:
  EmailNetwork:
    driver: bridge 