version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: gerenciamento-db
    restart: always
    environment:
      POSTGRES_USER: gerenciamento_user
      POSTGRES_PASSWORD: gerenciamento_pass
      POSTGRES_DB: gerenciamento
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # scripts iniciais (opcional)

  pgadmin:
    image: dpage/pgadmin4
    container_name: gerenciamento-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
